### ISSUE TITLE
Change random code generation

### ISSUE THREAD

**Issue by yuna878** [cuappdev/pollo-backend#174]
Don't generate code with alphabet 'O' & number '0'

**Comment by aliciaxw** [comment]
is this just for clarification for people wanting to join groups

**Comment by aliciaxw** [comment]
also what about '1' and 'l' and 'I'?

**Comment by yuna878** [comment]
Yes - so that people don't get confused. I think `1` `I` `L` are pretty distinguishable

**Comment by meganle** [comment]
edb5db35cd31972b0d9b8f72e197c0e39fb5fb27
